Testing
timafonseca/assignments pull request #3
Opened 2023-04-05 14:09 UTC by timafonseca

Unit tests

2023-04-05 14:34 UTC, MrCordeiro requested changes

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +#from pathlib import Path
No commented code!

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +    #root = Path()
```suggestion
    cur_path = Path(__file__)
```

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
>      file_path = OUTPUT_DIR / "pt_life_expectancy.csv"
**Comment**: you can delete this setup func after all testes consume from history

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/conftest.py
> +def loaded_data_test() -> pd.DataFrame:
Meaningful names: a conftest fixture is already implied to be only for use for testing, so the "_test" suffix is not necessary

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +    logging.info("Successfully saved data")
Move to a `loading_saving` module

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +def load_data() -> pd.DataFrame:
Move to `loading_saving` module

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/test_loading_saving.py
> +@mock.patch("pandas.DataFrame.to_csv")
```suggestion
@mock.patch("life_expectancy.loading_saving.pd.DataFrame.to_csv")
```

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/test_loading_saving.py
> +
Add side_effect to print something

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/test_loading_saving.py
> +
Add patch for .read_csv and assert the mock was called

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
Patch save_date / load_data OR pd.to_csv / pd.read_csv

2023-04-05 14:34 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
```python
def test_print(capfd):
  msg = "Hello from test"
  print(msg, end="")
  out, _ = capfd.readouterr()
  assert out == msg
``` 

To see the message, pass the `-s` option to the pytest command: `pytest -s PATH --cov`

2023-04-12 07:33 UTC, carolinafm216 requested changes
Bom trabalho colega!

2023-04-12 07:33 UTC, carolinafm216 commented on life_expectancy/tests/test_cleaning.py
> +from life_expectancy.main import main
porque importar do main e não do módulo? Penso que ficaria mais claro ao ler o código

2023-04-12 09:33 UTC, MrCordeiro commented on life_expectancy/tests/test_cleaning.py
> +from life_expectancy.main import main
@carolinafm216, vale a pena destacar se isso é apenas uma dúvida, uma sugestão ou se estás a requisitar uma alteração  ⭐

2023-04-12 15:23 UTC, merged