Add Strategy pattern and Region.py
timafonseca/assignments pull request #4
Opened 2023-05-17 11:29 UTC by timafonseca

2023-05-22 08:24 UTC, carolinafm216 reviewed
Bom trabalho!

2023-05-22 08:24 UTC, carolinafm216 commented on life_expectancy/loading_cleaning_saving.py
> +    def clean_data(self, df_input: pd.DataFrame, region: Region) -> pd.DataFrame:
Parece me apenas necessário fazer a função "load_data", visto que é a única coisa que muda quando estamos a importar ficheiros de extensões diferentes. Assim evitamos ter código repetido

2023-05-22 08:24 UTC, carolinafm216 commented on life_expectancy/main.py
> +        raise ValueError(f"Unsupported file extension: {extension}")
Boa ideia teres levantado a exceção!

2023-05-23 10:24 UTC, carolinafm216 requested changes
Bom trabalho!

2023-05-23 10:28 UTC, timafonseca reviewed
Muito obrigado Carolina! Consegues então dar o ultimo check, sff?

2023-05-23 10:28 UTC, timafonseca commented on life_expectancy/loading_cleaning_saving.py
> +    def clean_data(self, df_input: pd.DataFrame, region: Region) -> pd.DataFrame:
Da forma que fiz, preciso mesmo de ter assim porque acabo por ler os ficheiros de forma diferente e por isso preciso de ter dois load_data (um para cada caso)

2023-05-23 10:44 UTC, carolinafm216 reviewed
agora sem "Request changes"

2023-05-23 10:46 UTC, merged